#line 2 "lex.cc"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/root/flex/flex/skel.c,v 1.2 2004/05/07 00:28:17 jkh Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
static yyconst short int yy_acclist[329] =
    {   0,
        3,    3,    3,    3,    3,    3,   42,   40,   41,    3,
       40,   41,    1,   41,   40,   41,   40,   41,   40,   41,
       35,   40,   41,   36,   40,   41,   37,   40,   41,   40,
       41,   40,   41,   40,   41,   40,   41,   25,   40,   41,
       40,   41,   28,   40,   41,   32,   40,   41,   29,   40,
       41,   21,   40,   41,   21,   40,   41,   21,   40,   41,
       21,   40,   41,   21,   40,   41,   21,   40,   41,   21,
       40,   41,   21,   40,   41,   21,   40,   41,   19,   20,
       40,   41,   19,   20,   40,   41,   19,   20,   40,   41,
       19,   20,   40,   41,   19,   20,   40,   41,   19,   20,

       40,   41,   19,   20,   40,   41,   19,   20,   40,   41,
       19,   20,   40,   41,   40,   41,    3,   27,   14,   35,
        2,   39,   34,   20,   33,   25,    6,   31,   26,   30,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   20,   19,   20,   19,   20,   19,   20,   19,   20,
       19,   20,   19,   20,   19,   20,   19,   20,   19,   20,
       19,   20,   19,   20,   38,   21,   21,   21,   21,   21,
       21,   21,   15,   21,   11,   21,   21,   21,   19,   20,
       19,   20,   19,   20,   19,   20,   19,   20,   19,   20,
       19,   20,   15,   19,   20,   11,   19,   20,   19,   20,

       19,   20,   21,   21,   21,   21,   17,   21,   21,   21,
       10,   21,   21,   19,   20,   19,   20,   19,   20,   19,
       20,   17,   19,   20,   19,   20,   19,   20,   10,   19,
       20,   19,   20,   17,   10,   22,   21,   16,   21,   21,
       21,   21,   21,   21,   19,   20,   16,   19,   20,   19,
       20,   19,   20,   19,   20,   19,   20,   19,   20,   16,
       21,   21,   21,   21,   21,   18,   21,   19,   20,   19,
       20,   19,   20,   19,   20,   19,   20,   18,   19,   20,
        5,    4,   18,    7,   21,   21,   21,   21,   21,    7,
       19,   20,   19,   20,   19,   20,   19,   20,   19,   20,

        7,    4,   12,   21,   13,   21,    9,   21,    8,   21,
       12,   19,   20,   13,   19,   20,    9,   19,   20,    8,
       19,   20,   12,   13,    9,    8,   24,   23
    } ;

static yyconst short int yy_accept[260] =
    {   0,
        1,    2,    3,    4,    5,    6,    7,    8,   10,   13,
       15,   17,   19,   21,   24,   27,   30,   32,   34,   36,
       38,   41,   43,   46,   49,   52,   55,   58,   61,   64,
       67,   70,   73,   76,   79,   83,   87,   91,   95,   99,
      103,  107,  111,  115,  117,  118,  119,  119,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  121,  122,  123,  124,  125,  126,  127,  128,  129,
      130,  131,  132,  133,  134,  135,  136,  137,  138,  139,
      140,  141,  142,  143,  145,  147,  149,  151,  153,  155,
      157,  159,  161,  163,  165,  166,  166,  166,  166,  166,

      166,  166,  166,  166,  166,  166,  166,  166,  166,  167,
      168,  169,  170,  171,  172,  173,  175,  177,  178,  179,
      181,  183,  185,  187,  189,  191,  193,  196,  199,  201,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  204,  205,  206,  207,  209,
      210,  211,  213,  214,  216,  218,  220,  222,  225,  227,
      229,  232,  234,  234,  234,  234,  234,  234,  235,  235,
      235,  235,  235,  235,  236,  237,  237,  238,  240,  241,
      242,  243,  244,  245,  247,  250,  252,  254,  256,  258,
      260,  260,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  262,  263,  264,  265,  266,  268,  270,  272,
      274,  276,  278,  281,  281,  282,  282,  282,  282,  282,
      282,  283,  283,  284,  286,  287,  288,  289,  290,  293,
      295,  297,  299,  301,  302,  302,  302,  302,  302,  302,
      303,  303,  305,  307,  309,  311,  314,  317,  320,  323,
      324,  325,  326,  327,  327,  327,  328,  329,  329
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    1,    8,    9,
       10,   11,    1,   12,   13,   14,    1,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   21,   21,   29,   30,   31,   32,   33,
       21,   34,   35,   36,   37,   21,   38,   39,   40,   41,
        1,    1,    1,    1,   42,    1,   43,   42,   44,   45,

       46,   47,   48,   49,   50,   42,   42,   51,   52,   53,
       54,   55,   42,   56,   57,   58,   59,   42,   60,   61,
       62,   63,    1,   64,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1
    } ;

static yyconst short int yy_base[266] =
    {   0,
        0,    0,    0,    0,    0,    0,  552,  553,  549,  553,
      532,  544,   43,  545,  553,  553,  536,  534,    0,  531,
      529,  530,  524,  523,  519,    0,   37,   32,   35,   49,
       82,   50,   56,   60,  511,   77,   72,   78,   99,  110,
      108,  112,  100,  448,  509,  553,  501,  553,   80,   81,
       80,   84,   94,  127,   91,   93,   94,  102,  112,  130,
      502,  553,  553,  553,    0,  553,  489,  553,  553,  553,
      553,    0,  126,  122,  128,  140,  126,  135,  144,  132,
      137,  143,    0,  495,  164,  165,  167,  174,  175,  176,
      188,  191,  178,  184,  553,  172,  170,  168,  175,  185,

      170,  182,  184,  182,  197,  206,  206,  213,  209,  209,
      221,  224,  223,  220,  222,    0,    0,  213,  226,  245,
      246,  247,  254,  251,  249,  257,  494,  492,  248,  275,
      225,  247,  259,  260,  265,  264,  261,  262,  268,  264,
      271,  257,  272,  279,  278,  283,  286,  285,    0,  292,
      294,    0,  298,  318,  320,  323,  322,  490,  321,  324,
      489,  325,  301,  303,  312,  311,  312,  553,  319,  320,
      321,  327,  335,  553,  553,  337,  329,    0,  335,  340,
      341,  354,  347,  376,  450,  384,  381,  385,  386,  387,
      360,  553,  366,  367,  371,  372,  374,  373,  375,  385,

      372,  386,  396,  379,  385,  386,    0,  430,  432,  409,
      436,  438,  448,  418,  553,  423,  415,  409,  410,  435,
        0,  437,  553,    0,  430,  429,  437,  438,  393,  445,
      457,  462,  463,  553,  438,  437,  461,  467,  464,    0,
      457,    0,    0,    0,    0,  328,  327,  326,  197,  553,
      553,  553,  553,  463,  471,  553,  553,  553,  517,  522,
      112,  524,  527,  530,  535
    } ;

static yyconst short int yy_def[266] =
    {   0,
      258,    1,    1,    1,    1,    1,  258,  258,  258,  258,
      258,  259,  258,  260,  258,  258,  258,  258,  261,  258,
      258,  258,  258,  258,  258,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  258,  258,  258,  259,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      260,  258,  258,  258,  264,  258,  258,  258,  258,  258,
      258,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  264,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  262,  262,  262,  262,
      262,  262,  262,  263,  263,  263,  263,  263,  263,  263,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  262,  262,  262,  262,  262,  262,  263,  263,  263,
      263,  263,  263,  258,  258,  258,  258,  258,  258,  258,
      265,  258,  258,  262,  262,  262,  262,  262,  263,  263,
      263,  263,  263,  258,  258,  258,  258,  258,  258,  265,
      258,  262,  262,  262,  262,  263,  263,  263,  263,  258,
      258,  258,  258,  258,  258,  258,  258,    0,  258,  258,
      258,  258,  258,  258,  258
    } ;

static yyconst short int yy_nxt[618] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,    8,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       26,   27,   26,   28,   29,   26,   30,   26,   26,   31,
       32,   26,   26,   26,   33,   26,   26,   34,   26,   26,
       26,   35,   35,   36,   35,   37,   38,   35,   39,   35,
       35,   40,   41,   35,   35,   35,   42,   35,   35,   43,
       35,   35,   35,   44,   49,   50,   51,   52,   73,   53,
       74,   75,   54,   55,   56,   57,   76,   58,   59,   83,
       60,   80,   81,   82,   83,   83,   49,   50,   51,   52,
       73,   53,   74,   75,   54,   55,   56,   57,   76,   58,

       59,   77,   60,   80,   81,   82,   83,   83,   85,   78,
       86,   96,   97,   79,   87,   83,   65,   83,   98,   83,
       99,  100,  103,   94,   77,  104,   88,  105,  106,   89,
       85,   78,   86,   96,   97,   79,   87,   90,   93,   92,
       98,   91,   99,  100,  103,   94,  101,  104,   88,  105,
      106,  107,   89,  108,  102,  109,  110,  111,  112,   90,
       93,   92,  113,   91,  114,  115,  116,  117,  118,  101,
      119,   83,   83,  107,   83,  108,  102,  109,  110,  111,
      112,   83,   83,   83,  113,   83,  114,  115,  116,  117,
      118,   83,  119,  120,  121,   83,  124,  123,   83,  133,

      122,  131,  132,  134,   83,  135,  126,  136,  137,  129,
      127,  130,  138,  125,  139,  120,  121,  140,  124,  123,
      141,  133,  122,  131,  132,  134,  128,  135,  126,  136,
      137,  129,  127,  130,  138,  125,  139,  142,  143,  140,
      144,  145,  141,  146,  147,  148,  149,  150,  128,  151,
      152,  153,   83,   83,   83,   83,   83,  163,   83,  142,
      143,   83,  144,  145,   83,  146,  147,  148,  149,  150,
      156,  151,  152,  153,  158,  157,  159,  154,  165,  163,
      155,  164,   83,  166,  160,  161,  167,  168,  169,  170,
      171,  172,  156,  173,  174,  175,  158,  157,  159,  154,

      162,  165,  155,  164,  176,  166,  160,  161,  167,  168,
      169,  170,  171,  172,  177,  173,  174,  175,  178,  179,
      180,  181,  162,  182,  183,   83,  176,   83,   83,   83,
       83,   83,   83,   83,   83,   83,  177,  191,  192,  193,
      178,  179,  180,  181,  194,  182,  183,  195,  196,  197,
      188,  190,  198,  189,  184,  185,  186,  187,  199,  191,
      192,  193,  200,  201,  202,  203,  194,  204,  205,  195,
      196,  197,  188,  190,  198,  189,  184,  185,  186,  187,
      199,  206,  207,   83,  200,  201,  202,  203,   83,  204,
      205,   83,   83,   83,   83,  214,  215,  216,  217,  218,

       83,  219,  220,  206,  207,  221,  222,  223,  210,  224,
      226,  208,  211,  212,  209,  225,   83,  214,  215,  216,
      217,  218,  213,  219,  220,  227,  228,  221,  222,  223,
      210,  224,  226,  208,  211,  212,  209,   83,  225,   83,
      231,  234,  235,   83,  213,   83,  236,  227,  228,  237,
      238,  230,   83,  229,  239,   83,  241,   83,  242,  243,
      244,  245,  231,  234,   83,  235,  250,  251,  236,   83,
       83,  237,  238,  246,  230,  229,  232,  239,  233,  241,
      242,  243,  244,  245,  252,  248,  249,  247,  250,  251,
      253,  254,  255,  256,  257,  246,   83,   83,  232,   83,

      233,   83,   83,   67,   62,   48,  252,  248,  249,  247,
       45,   95,  253,  254,  255,  256,  257,   47,   83,   47,
       47,   47,   61,   61,   61,   61,   61,   72,   72,   84,
       84,   84,   83,   83,   83,  240,   71,  240,  240,  240,
       70,   69,   68,   67,   66,   64,   63,   62,   48,   46,
       45,  258,    7,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258
    } ;

static yyconst short int yy_chk[618] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   13,   13,   13,   13,   27,   13,
       28,   29,   13,   13,   13,   13,   30,   13,   13,   37,
       13,   32,   33,   34,   36,   38,   13,   13,   13,   13,
       27,   13,   28,   29,   13,   13,   13,   13,   30,   13,

       13,   31,   13,   32,   33,   34,   39,   43,   36,   31,
       37,   49,   50,   31,   38,   41,  261,   40,   51,   42,
       52,   53,   55,   43,   31,   56,   39,   57,   58,   40,
       36,   31,   37,   49,   50,   31,   38,   40,   42,   41,
       51,   40,   52,   53,   55,   43,   54,   56,   39,   57,
       58,   59,   40,   60,   54,   73,   73,   74,   75,   40,
       42,   41,   76,   40,   77,   78,   79,   80,   81,   54,
       82,   85,   86,   59,   87,   60,   54,   73,   73,   74,
       75,   88,   89,   90,   76,   93,   77,   78,   79,   80,
       81,   94,   82,   85,   85,   91,   88,   87,   92,   97,

       86,   96,   96,   98,  249,   99,   90,  100,  101,   93,
       91,   94,  102,   89,  103,   85,   85,  104,   88,   87,
      105,   97,   86,   96,   96,   98,   92,   99,   90,  100,
      101,   93,   91,   94,  102,   89,  103,  106,  107,  104,
      108,  109,  105,  110,  111,  112,  113,  114,   92,  115,
      118,  119,  120,  121,  122,  129,  125,  131,  124,  106,
      107,  123,  108,  109,  126,  110,  111,  112,  113,  114,
      122,  115,  118,  119,  124,  123,  125,  120,  133,  131,
      121,  132,  130,  134,  126,  129,  135,  136,  137,  138,
      139,  140,  122,  141,  142,  143,  124,  123,  125,  120,

      130,  133,  121,  132,  144,  134,  126,  129,  135,  136,
      137,  138,  139,  140,  145,  141,  142,  143,  146,  147,
      148,  150,  130,  151,  153,  154,  144,  155,  159,  157,
      156,  160,  162,  248,  247,  246,  145,  163,  164,  165,
      146,  147,  148,  150,  166,  151,  153,  167,  169,  170,
      159,  162,  171,  160,  154,  155,  156,  157,  172,  163,
      164,  165,  173,  176,  177,  179,  166,  180,  181,  167,
      169,  170,  159,  162,  171,  160,  154,  155,  156,  157,
      172,  182,  183,  184,  173,  176,  177,  179,  187,  180,
      181,  186,  188,  189,  190,  191,  193,  194,  195,  196,

      229,  197,  198,  182,  183,  199,  200,  201,  187,  202,
      204,  184,  188,  189,  186,  203,  210,  191,  193,  194,
      195,  196,  190,  197,  198,  205,  206,  199,  200,  201,
      187,  202,  204,  184,  188,  189,  186,  208,  203,  209,
      210,  214,  216,  211,  190,  212,  217,  205,  206,  218,
      219,  209,  230,  208,  220,  213,  222,  185,  225,  226,
      227,  228,  210,  214,  231,  216,  235,  236,  217,  232,
      233,  218,  219,  230,  209,  208,  211,  220,  212,  222,
      225,  226,  227,  228,  237,  232,  233,  231,  235,  236,
      238,  239,  241,  254,  255,  230,  161,  158,  211,  128,

      212,  127,   84,   67,   61,   47,  237,  232,  233,  231,
       45,   44,  238,  239,  241,  254,  255,  259,   35,  259,
      259,  259,  260,  260,  260,  260,  260,  262,  262,  263,
      263,  263,  264,  264,  264,  265,   25,  265,  265,  265,
       24,   23,   22,   21,   20,   18,   17,   14,   12,   11,
        9,    7,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.ll"
#define INITIAL 0
/*
** lex.l -- lexer for lparse
**
** Copyright (C) 1999-2007 Tommi Syrjänen <Tommi.Syrjanen@hut.fi>
**  
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**  
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**  
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
**  
*/
#line 23 "lex.ll"
#include "config.h"
#include "parsetree.h"
#include "symbol.h"
#include "parse.h"
#include "error.h"
#include <string.h>

extern int lineno;
extern int return_symbol;
extern int return_funcsymbol;


int par_depth = 0;
int inside_definition = 0;
int newline_read = 0;

int next_input_file()
{
  static FILE *yyin = 0;
  static int current_file = 0;

  if (!newline_read)
    lineno++;
  
  if ( current_file < sys_data.num_input_files) {
    if ( yyin ) { fclose(yyin); }
    yyin = fopen(sys_data.input_files[current_file], "r");
    if (!yyin) {
      error(SYS_ERR, "cannot open input file %s",
	    sys_data.input_files[current_file++]); 
    }
    yy_switch_to_buffer( yy_create_buffer( yyin, YY_BUF_SIZE));
    sys_data.file_start_lines[current_file++] = lineno;
  } else {
    return 0;
  }
  return 1;
}

#define PAREN 1

#define DEFINITION 2

#define YY_NEVER_INTERACTIVE 1
/* operators */
#line 701 "lex.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 109 "lex.ll"

#line 854 "lex.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 259 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 553 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 110 "lex.ll"
{ lineno++; newline_read = 1; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 111 "lex.ll"
{ newline_read = 1; lineno++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 112 "lex.ll"
{ newline_read = 0; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 113 "lex.ll"
{ yylval.s = clone_string(yytext); return OPTION; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 114 "lex.ll"
{ return VARIABLEDEF; }	
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 115 "lex.ll"
{ newline_read = 0;return IF; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "lex.ll"
{ newline_read = 0;return COMPUTE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 117 "lex.ll"
{ newline_read = 0;return MINIMIZE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 118 "lex.ll"
{ newline_read = 0;return MAXIMIZE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 119 "lex.ll"
{ newline_read = 0;return SHOW; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 120 "lex.ll"
{ newline_read = 0;return NOT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 121 "lex.ll"
{ newline_read = 0;return EXTERNAL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 122 "lex.ll"
{ newline_read = 0;inside_definition = 1; return FUNCTION; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 123 "lex.ll"
{ newline_read = 0; if (!sys_data.drop_quotes) {
                                     yylval.s = clone_string(yytext);
                                    } else {
                                     yylval.s = clone_string(yytext+1);
                                     yylval.s[strlen(yylval.s)-1] =
				     '\0';
                                    }
                  return IDENTIFIER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 131 "lex.ll"
{ newline_read = 0; return MOD; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 132 "lex.ll"
{ newline_read = 0; inside_definition = 1; return CONST; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 133 "lex.ll"
{ newline_read = 0; return HIDE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 134 "lex.ll"
{ return WEIGHT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 135 "lex.ll"
{ newline_read = 0; if (function_table->Lookup(yytext) >= 0) { 
			yylval.s = clone_string(yytext);
			return FUNCSYMBOL;
		  } else REJECT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 139 "lex.ll"
{ newline_read = 0; yylval.s = clone_string(yytext); return IDENTIFIER; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 140 "lex.ll"
{ newline_read = 0; yylval.s = clone_string(yytext);
				    return VARIABLE;} 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 142 "lex.ll"
{ newline_read = 0; yylval.s = clone_string(yytext);
				    return TYPE;} 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 144 "lex.ll"
{ newline_read = 0; yylval.s = clone_string(yytext);
				    return PREDICATE;} 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 146 "lex.ll"
{ newline_read = 0; yylval.s = clone_string(yytext);
				    return NONDOMAIN;} 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 148 "lex.ll"
{ newline_read = 0; yylval.l = strtol(yytext,NULL,10);
		  return NUMBER;} 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 150 "lex.ll"
{ newline_read = 0; return EQ; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 151 "lex.ll"
{ newline_read = 0; return NEQ; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 152 "lex.ll"
{ newline_read = 0; return LT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 153 "lex.ll"
{ newline_read = 0; return GT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 154 "lex.ll"
{ newline_read = 0; return GE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 155 "lex.ll"
{ newline_read = 0; return LE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 156 "lex.ll"
{ newline_read = 0; return ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 157 "lex.ll"
{ newline_read = 0; return DOTS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 158 "lex.ll"
{ newline_read = 0; return COMMAS; } 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 159 "lex.ll"
{ newline_read = 0; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 160 "lex.ll"
{ newline_read = 0; par_depth++; return '('; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 161 "lex.ll"
{ newline_read = 0; par_depth--; return ')';  }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 162 "lex.ll"
{ newline_read = 0; return NORM; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 163 "lex.ll"
{ newline_read = 0; return EXP; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PAREN):
case YY_STATE_EOF(DEFINITION):
#line 164 "lex.ll"
{ if ((sys_data.num_input_files == 0) ||
                      (!next_input_file())) {
                    yyterminate();
                  }
                }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 169 "lex.ll"
{ newline_read = 0; return *yytext; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 170 "lex.ll"
ECHO;
	YY_BREAK
#line 1168 "lex.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 259 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 259 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 258);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 170 "lex.ll"
